// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czmviaiqnbrkdqulqqkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6bXZpYWlxbmJya2RxdWxxcWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTA0NjcsImV4cCI6MjA2OTUyNjQ2N30.2MxYJ8fQ7r5hsYYZKykSXpfs9HoupfWzqjDHcVKAwLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});